# Generated by Django 2.1.2 on 2018-11-07 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_remove_scene_root_component'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='scene',
        ),
        migrations.AddField(
            model_name='route',
            name='component',
            field=models.ForeignKey(default='a10b236d-cedb-4d02-9389-aa89e155ed21', on_delete=django.db.models.deletion.CASCADE, to='components.ComponentInstance'),
            preserve_default=False,
        ),
    ]
