# Generated by Django 2.1.2 on 2018-11-07 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scene',
            name='root_component',
        ),
    ]
