# Generated by Django 2.1.2 on 2018-11-07 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_remove_scene_root_component'),
        ('routes', '0002_auto_20181107_1905'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scene',
        ),
    ]
